// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetProfiles():Promise<Array<main.ProfileInfo>>;

export function IsBuilding():Promise<boolean>;

export function SelectCUEFile():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectOutputPath(arg1:string):Promise<string>;

export function StartBuild(arg1:main.BuildConfig):Promise<void>;
