// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function IsBuilding() {
  return window['go']['main']['App']['IsBuilding']();
}

export function SelectCUEFile() {
  return window['go']['main']['App']['SelectCUEFile']();
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectOutputPath(arg1) {
  return window['go']['main']['App']['SelectOutputPath'](arg1);
}

export function StartBuild(arg1) {
  return window['go']['main']['App']['StartBuild'](arg1);
}
